### ISSUE TITLE
Update storybook

### ISSUE THREAD

**Issue by Tomekmularczyk** [Tomekmularczyk/rollup-styled-jsx#10]
Update storybook dependency

![image](https://user-images.githubusercontent.com/12544704/94792047-be922480-03d8-11eb-9d79-b7d9b679cb58.png)

**Comment by saraogipraveen** [comment]
I can take this one, please assign @Tomekmularczyk

**Comment by Tomekmularczyk** [comment]
go ahead @saraogipraveen

**Comment by saraogipraveen** [comment]
@Tomekmularczyk  Ready for review
