### ISSUE TITLE
Update Rollup

### ISSUE THREAD

**Issue by Tomekmularczyk** [Tomekmularczyk/rollup-styled-jsx#9]
Update Rollup to v2

**Comment by therealansh** [comment]
Hey @Tomekmularczyk can i take this one?

**Comment by Tomekmularczyk** [comment]
@therealansh go ahead!

**Comment by Tomekmularczyk** [comment]
@therealansh did you try to run `npm run release` to see if it build without a problem?

**Comment by therealansh** [comment]
yes @Tomekmularczyk , it runs smoothly and produces prod.js file
